# Generated by Django 2.2.28 on 2024-03-19 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('letthemcookapp', '0002_auto_20240319_1320'),
        ('letthemcookapp', '0002_auto_20240318_2323'),
    ]

    operations = [
    ]
