# Generated by Django 5.0.3 on 2024-03-21 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "letthemcookapp",
            "0004_alter_recipe_id_alter_recipe_picture_alter_review_id_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="recipe",
            name="average_rating",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="recipe",
            name="saves",
            field=models.IntegerField(default=0),
        ),
    ]
