# Generated by Django 5.0.3 on 2024-03-21 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("letthemcookapp", "0005_auto_20240321_1308"),
        ("letthemcookapp", "0005_recipe_average_rating_recipe_saves"),
    ]

    operations = []
