# Generated by Django 5.0.3 on 2024-03-21 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("letthemcookapp", "0006_merge_20240321_1447"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipe",
            name="average_rating",
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name="recipe",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="review",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="save",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
